services:
  mssqlserver2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dev-mssqlserver2019
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    ports:
      - "14333:1433"
    volumes:
      - mssql2019_data:/var/opt/mssql
    restart: always

  mssqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-mssqlserver2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    ports:
      - "14334:1433"
    volumes:
      - mssql2022_data:/var/opt/mssql
    restart: always

  postgresql16:
    image: postgres:16.4-alpine
    container_name: dev-postgresql16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis7:
    image: redis:7.2.5-alpine
    container_name: dev-redis7
    command: redis-server --requirepass Password123!
    ports:
      - "6380:6379"
    volumes:
      - redis7_data:/data
    restart: always

volumes:
  postgres_data:
  mssql2019_data:
  mssql2022_data:
  redis7_data:
