version: '3'

tasks:
  restart:
    desc: 重新啟動開發環境 (可指定服務，例如 task restart -- mssqlserver2019)
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  restart:all:
    desc: 重新啟動所有服務
    cmds:
      - docker compose up -d

  restart:mssql2019:
    desc: 重新啟動 SQL Server 2019
    cmds:
      - docker compose up -d mssqlserver2019

  restart:mssql2022:
    desc: 重新啟動 SQL Server 2022
    cmds:
      - docker compose up -d mssqlserver2022

  restart:pg16:
    desc: 重新啟動 PostgreSQL 16
    cmds:
      - docker compose up -d postgresql16

  restart:redis7:
    desc: 重新啟動 Redis 7
    cmds:
      - docker compose up -d redis7

  reset:
    desc: 重置開發環境資料 (可指定服務，例如 task reset -- mssqlserver2019)
    cmds:
      - docker compose down -v {{.CLI_ARGS}}
      - docker compose up -d {{.CLI_ARGS}}

  reset:all:
    desc: 重置所有服務資料 (不保留)
    cmds:
      - docker compose down -v
      - docker compose up -d

  reset:mssql2019:
    desc: 重置 SQL Server 2019 資料 (不保留)
    cmds:
      - docker compose down -v mssqlserver2019
      - docker compose up -d mssqlserver2019

  reset:mssql2022:
    desc: 重置 SQL Server 2022 資料 (不保留)
    cmds:
      - docker compose down -v mssqlserver2022
      - docker compose up -d mssqlserver2022

  reset:pg16:
    desc: 重置 PostgreSQL 16 資料 (不保留)
    cmds:
      - docker compose down -v postgresql16
      - docker compose up -d postgresql16

  reset:redis7:
    desc: 重置 Redis 7 資料 (不保留)
    cmds:
      - docker compose down -v redis7
      - docker compose up -d redis7
